// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAlternativeBuildingNumbers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAlternativeBuildingNumbers));
        
        string IMigrationMetadata.Id
        {
            get { return "201608101435382_AddAlternativeBuildingNumbers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
